/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.production.jsonc --include-runtime=false --strict-vars=false --env-interface=ProductionBindings src/production-bindings.d.ts` (hash: 65f6061fb7b9330a9ace62ca6eb03bf9)
interface __BaseEnv_ProductionBindings {
	STORAGE: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	AI: Ai;
	ASSETS: Fetcher;
	API_URL: string;
	WEB_URL: string;
	EMAIL_FROM: string;
	AI_MONTHLY_TOKEN_LIMIT: string;
	AI_MODEL: string;
	BETTER_AUTH_SECRET: string;
	CanvasAgent: DurableObjectNamespace<import("./production").CanvasAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./production");
		durableNamespaces: "CanvasAgent";
	}
	interface Env extends __BaseEnv_ProductionBindings {}
}
interface ProductionBindings extends __BaseEnv_ProductionBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "API_URL" | "WEB_URL" | "EMAIL_FROM" | "AI_MONTHLY_TOKEN_LIMIT" | "AI_MODEL" | "BETTER_AUTH_SECRET">> {}
}

export type { ProductionBindings }
